{% set name = "rfc3986" %}
{% set version = "2.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97aacf9dbd4bfd829baad6e6309fa6573aaf1be3f6fa735c8ab05e46cecb261c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - rfc3986
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://rfc3986.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Validating URI References per RFC 3986
  description: |
    A Python implementation of RFC 3986 including validation and authority parsing.
  doc_url: https://rfc3986.readthedocs.io
  dev_url: https://github.com/python-hyper/rfc3986

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
    - sigmavirus24
    - bollwyvl
