travis:
  secure:
    BINSTAR_TOKEN: WKMY4CDV2vtz+jrv8y670gNWSiEqz9j2U1y5NE33O5dyetYobN8+qUnUGiyHgEf6mAj6vu30CBGVCHwoWBFmhvZDLHwjFpkvrfiQ+MwZ1TCWGgiLR1fAB0WaT6tw5ooxg0L+Ye2ULwDKP4Jn/pnFrJtgLY8T3eR/CzOiiiFfGiwsvroogeZjXaKu/dJP10DMvzzPE5+Bt/qkdpTUys4QFvzY1zDqP3s8uqZioVmTyjOnQUYtGf0U/NM8lKZ/LkSxVmqL2dg9IgN7d736EPmC5Qp5gcwFfCQvf9zJ00FPSBRCUAYXkTls8uyotxCZ4QWsuKlZOj4c5MvbzkaR9swKjBK/aBwXElTtMUcKTPiIpfnZsaxPDbiTlJWAwArO0Ey8fqSx7aeeCegkV+NHGg5quiM6L1YEq+rviQ7yoTPbTT87ncNW5xM9A9oxt8LfPjHYNOLON1OFpCDdTJj413sRl95CHeTC4+ry9fV/ZqnR8IDS7KnRPlDI2d1DSVv0vq8zCrSvd/TZA96BSL6J/msARwN9/kFUv1EWuaebFhJR/I0WnRAg3p6z2+WhiwFriT9Iq39wE39KfV013JAp1O7PrpB5Vfksfl5FtoFmI1+BIHY12zt/AprNHlprN2Ztd9u4xZ12ci1JRORHWAok1cnB5lTVn69kTUT76ltXYs6k4y0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
