travis:
  secure:
    BINSTAR_TOKEN: U4N31Uz0fVA9FFW1ICNq/We7oLAmmF3AtPa+SnymZLgtgee8rbngfPbYvdP4vwcVxG2Tkf/t0Nkm0A85g98JzvxMEL7P6hTOk4Whd5pilAMIvuEhagWMazzWziGdT6LhtwlxmPxoYxqpJ3xQdsgd8SAL63r2HqTXvIFfpZog/k4zK7v2tWG4l093/f++8CLTM6k1ZdBVhF1XAP69DYvibXSU8HNwW39PEDNDqm+/KQ0qBWQqaSM6ieecXNqPoJ6NnBVxi2Wza7O46eUUbETeKQeXN6+zGLX1dmPe1yRBVAtiFAxDEuodBhjET8JjKnQmV3ZMW4XIy5CKs0ObI0nijuzNpc40y8m5AnUxlhOUVFEWr28CDIEMcC8vJhVukGEaTWXVWU503Gsu6s91GXSmDdYn2Nzxbol2/RsYSVt+evfCZfAeCW7+ysUTQV4BIg4lRC7KDxP100xaWf2qtExRYsXgXFvjXu2x2d0ch0icTcwOQzigwLcz+/HHdrneZXUAEG3TGnIgv5CW6XexDj6/CfwOHCMSR3F2a5Yqli+Q3B1A8dpuYsAaUWeUtqzBEEeiu+vd8m6l/saKaxmy1T3rnErk5UV5B1IT9lxeESOR1cIuYpW3jhNTXawrq7nyqZVCTXsnrbCmNAkvsJXZEUtJbpF6pZoe5eC3byRe8s6fyW8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
