travis:
  secure:
    BINSTAR_TOKEN: hPTmzcoM2O8tKISFsU9cezBrthW3mqV+IftRbktK/vo+VKyPYytf13Yf795A6tlwZnvNW/Q0HPyH2JUv9J4YvW/l3czt33cX5B3Ld1HJgC5s0alwbf4Q76bcIO9/YIRczVwUpsaE/w4ANVmY/JcHGHx/KcisTZpknsNn7UAXlCbdSDiuOrNoO4pk5KSCqY3luX8zBQ48AgqiJSg/jT0xhNzhtJfIm9KkqYhkuEq66dxRX3sUcGhlSIR54G7cPuJlMePSe9Be9XwQStzeSQC/5q7Zo+237VJlLiRUXZ4iOXFIhfPecoCbKKapTpmcVbJFSUgq21XgKmzPHC/wP02qSu/WelBa10CpaD3u/1/jrRsg/LdG97xaF7zGVgpTxo9zaAYiT1HQ3BAEOgRqS++AdjrbIsB1nB3LEwViqoBaH7+pWaUZlLV9ZUbTsaJaT2jqlBcdkjIS3V82tkK206Wh6wtdkahnk53HmngRkoYXu+s1XJ7QsE6QEME+5rtOHnavCwdoXNyAjamCWcudsG/iPbZxI8qQDLxpsq5yTCogXJxL45u+Cipy6hLyITVoh2runQoGOwqAMXifzPXkGIVdiJWRrFYeDI/5eVnfBAIvswp2HBhVYOABzo7kCT+a9baNyUtncfzJJojlNW1R/cKU3M9wS70VPsT4WYquy4ezxB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
