travis:
  secure:
    BINSTAR_TOKEN: id5zDpX4SUjSN6OBXYfKo5uWoEKEBIgbzEMGe1oFFHloXJDdRdrjFEwphxThMpKdVTDlxXd8thgkWOdZMKYY9VAKEdgdB2vNMRvR+eAma3LDirQ1elrIwRLAf3kJx3AOlaH6yNJktWHime5ZEds5vNE1sbkM2prmfuOQwxl1SwEOr2L3E4xAJllFfHmV8RDkZf7elAIZ9fNWLGiU3zxo8CoulwY+PDLEJPy1FfJ031k78CXqYodqltEZb2ULUoGdhlR+0j+V8OpuuD7ZwJmhWmeSIBnCz7AXv58P1y2edGAPN7SvY4Rh+AL5MnHPedxkyUgyZZDzJ4JZKOlvN1/0sVwsVKMUH9JU4FhNK2wflb99O31tz95H67z71sbHSIgtcw91MpC9YUwTG67YARvZiitNzmr4d36vUhJS5P2rK5fYfoKYm+/X6TtaV0RiAv82XBqreg8d3F5dphBO58UIiOKnJL68ihYfERwC7N2d0crzhlFU3Z4dAL+DURp1c/aTf88jLq0iErkzslcRfbJ5ftayHD4q1V7rTu3pVGKoYONtsJEt2KGeHBTPCISS6nB8epk1Uxmce9B34+Wz7ykm1sVBdQb5EFhCFsH3fVSToHBm+nytjzzn0mHtBVrrPPwAjphIjYdRyKnhxtYt3pwWIIiREZXZEqnWNY7nTIRn/6o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
