travis:
  secure:
    BINSTAR_TOKEN: gN8PbkIuaqaK6uKKyFklJPIcpNJXdq62sujp4vHQDUD64d1AQD4dzfkMR2szL0Ykx1sQUISb0R9A9fhtjrFZ3wugMvYsIyoQjy8v+49ADQwmVEoLeC/0bsKn7Ov+D96/M7RAkURq+l0eELiKAwCzD7YE4hlKJOHXlUOz/Q3G6VmfVsEtLCV2daE/FSSKWY+K/wurTZvjeorluvEfDdGj1VH+nwf1mddEnWdK2Et9aqX56/KI7FNqRZGP8eM6BNPrKIPWsrjcbOq0PV8EpDFkj8JaWK5uIa2hTY88XUzgYmIXKdbmpDEimqdheZoY+S999o9l+wagN1DLqWNkWrl++90MfXbLJlas7bFuz89pTbxl6y5CVBuscvwN/bTmFpCo/tefNxrLXpxXszMay1FYuyLTznP3aIy7oPQGk4GN22lDJXVUHM1/vwMKZXQB0YfoyIA6JDkahsOD8xxmYd8wZX2CsW5lc2KZQd3LnSibxZYgwDtB1C2uUvK6/bToaiUPPRmxx0rAJC+y/BLNB4EuG4+FibRGx9nlxjVx0austHFDMYkTNmvrBGxk11K0uWxWD/YVHkWTgXc9wOYyE0mgFyjrVj2Wu8Yb47Jya9XI/vzKCLJBXewEx+ZSemejGSiEn4RmQjI1yGSJchIR98Ae6sKcxXD2fFX6ARfyc+SVntw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
